# Generated by Django 2.0.3 on 2018-08-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotrees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='image',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
